/* soapClient.c
   Generated by gSOAP 2.7.9k from Documents/WS/currentTime.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.9k 2014-05-27 14:34:38 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__currentTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, time_t *response)
{	struct ns__currentTime soap_tmp_ns__currentTime;
	struct ns__currentTimeResponse *soap_tmp_ns__currentTimeResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:18000";
	soap->encodingStyle = NULL;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__currentTime(soap, &soap_tmp_ns__currentTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__currentTime(soap, &soap_tmp_ns__currentTime, "ns:currentTime", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__currentTime(soap, &soap_tmp_ns__currentTime, "ns:currentTime", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_time(soap, response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__currentTimeResponse = soap_get_ns__currentTimeResponse(soap, NULL, "ns:currentTimeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (response && soap_tmp_ns__currentTimeResponse->response)
		*response = *soap_tmp_ns__currentTimeResponse->response;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
